

const beastData = [
    {
        "Name": "Shenghuang",
        "Star": "2",
        "LE": "1500",
        "STR": "1000",
        "VE": "1000",
        "DEX": "1000",
        "LE_gain": "20",
        "STR_gain": "20",
        "VE_gain": "20",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "1"
    },
    {
        "Name": "Pi Xiu",
        "Star": "2",
        "LE": "1000",
        "STR": "1000",
        "VE": "1000",
        "DEX": "1500",
        "LE_gain": "20",
        "STR_gain": "20",
        "VE_gain": "20",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "2"
    },
    {
        "Name": "Chi Wen",
        "Star": "2",
        "LE": "1000",
        "STR": "1000",
        "VE": "1500",
        "DEX": "1000",
        "LE_gain": "20",
        "STR_gain": "20",
        "VE_gain": "20",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "3"
    },
    {
        "Name": "Bi'an",
        "Star": "2",
        "LE": "1000",
        "STR": "1500",
        "VE": "1000",
        "DEX": "1000",
        "LE_gain": "20",
        "STR_gain": "20",
        "VE_gain": "20",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "4"
    },
    {
        "Name": "Red Phoenix",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "43,44",
        "Region_Boost": "0.08",
        "Region": "",
        "BeastId": "5"
    },
    {
        "Name": "Azure Phoenix",
        "Star": "3",
        "LE": "2500",
        "STR": "2500",
        "VE": "2500",
        "DEX": "3000",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "39,40",
        "Region_Boost": "0.08",
        "Region": "",
        "BeastId": "6"
    },
    {
        "Name": "Baize",
        "Star": "3",
        "LE": "2500",
        "STR": "2500",
        "VE": "3000",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "48,50",
        "Region_Boost": "0.08",
        "Region": "",
        "BeastId": "7"
    },
    {
        "Name": "Xiezhi",
        "Star": "3",
        "LE": "2500",
        "STR": "3000",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "41,42,45",
        "Region_Boost": "0.08",
        "Region": "",
        "BeastId": "8"
    },
    {
        "Name": "Ninetails",
        "Star": "3",
        "LE": "2500",
        "STR": "2800",
        "VE": "2800",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "47,49,46",
        "Region_Boost": "0.08",
        "Region": "",
        "BeastId": "9"
    },
    {
        "Name": "Bliss Lion",
        "Star": "3",
        "LE": "2500",
        "STR": "3000",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.08",
        "Region": "1",
        "BeastId": "86"
    },
    {
        "Name": "Azure Dragon",
        "Star": "4",
        "LE": "5000",
        "STR": "5000",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "11"
    },
    {
        "Name": "Jiuying",
        "Star": "4",
        "LE": "5000",
        "STR": "5500",
        "VE": "5000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "12"
    },
    {
        "Name": "Heavenly Kun",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "51,52,53,54",
        "Region_Boost": "0.15",
        "Region": "",
        "BeastId": "13"
    },
    {
        "Name": "Flood Dragonling",
        "Star": "1",
        "LE": "500",
        "STR": "500",
        "VE": "500",
        "DEX": "500",
        "LE_gain": "20",
        "STR_gain": "20",
        "VE_gain": "20",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "14"
    },
    {
        "Name": "Abomination Witch",
        "Star": "6",
        "LE": "13000",
        "STR": "9500",
        "VE": "9500",
        "DEX": "13000",
        "LE_gain": "70",
        "STR_gain": "60",
        "VE_gain": "60",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "4",
        "BeastId": "118"
    },
    {
        "Name": "Yinglong",
        "Star": "6",
        "LE": "12500",
        "STR": "12500",
        "VE": "12500",
        "DEX": "12500",
        "LE_gain": "75",
        "STR_gain": "75",
        "VE_gain": "75",
        "DEX_gain": "75",
        "ServantIds": "55,56,57",
        "Region_Boost": "0.18",
        "Region": "",
        "BeastId": "16"
    },
    {
        "Name": "Hell Steed",
        "Star": "4",
        "LE": "5500",
        "STR": "5500",
        "VE": "5500",
        "DEX": "5500",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.12",
        "Region": "",
        "BeastId": "17"
    },
    {
        "Name": "Ninth-Hell Steed",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.15",
        "Region": "",
        "BeastId": "18"
    },
    {
        "Name": "River God",
        "Star": "6",
        "LE": "15000",
        "STR": "15000",
        "VE": "15000",
        "DEX": "15000",
        "LE_gain": "80",
        "STR_gain": "80",
        "VE_gain": "80",
        "DEX_gain": "80",
        "ServantIds": "55,56,57",
        "Region_Boost": "0.18",
        "Region": "",
        "BeastId": "19"
    },
    {
        "Name": "YuanChu",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.12",
        "Region": "",
        "BeastId": "20"
    },
    {
        "Name": "Tien YuanChu",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.15",
        "Region": "",
        "BeastId": "21"
    },
    {
        "Name": "Jue Ru",
        "Star": "4",
        "LE": "5000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "51,52,53,54",
        "Region_Boost": "0.12",
        "Region": "",
        "BeastId": "22"
    },
    {
        "Name": "Snowy Jue Ru",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "51,52,53,54",
        "Region_Boost": "0.15",
        "Region": "",
        "BeastId": "23"
    },
    {
        "Name": "Kyrin",
        "Star": "4",
        "LE": "5000",
        "STR": "5000",
        "VE": "5000",
        "DEX": "5500",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "10"
    },
    {
        "Name": "Abyss Chimera",
        "Star": "5",
        "LE": "9000",
        "STR": "7000",
        "VE": "9000",
        "DEX": "7000",
        "LE_gain": "60",
        "STR_gain": "40",
        "VE_gain": "60",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "116"
    },
    {
        "Name": "Buddha Dragon Horse",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "50"
    },
    {
        "Name": "LoveBird",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "5000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "27"
    },
    {
        "Name": "Thunder",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "35"
    },
    {
        "Name": "Phoenix",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "5000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "29"
    },
    {
        "Name": "Fly Dragon",
        "Star": "4",
        "LE": "5000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "37"
    },
    {
        "Name": "QiongQi",
        "Star": "4",
        "LE": "6000",
        "STR": "6000",
        "VE": "6000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "24"
    },
    {
        "Name": "QingYuan",
        "Star": "4",
        "LE": "5500",
        "STR": "5000",
        "VE": "5500",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "31"
    },
    {
        "Name": "Chaos Chimera",
        "Star": "6",
        "LE": "15000",
        "STR": "10000",
        "VE": "15000",
        "DEX": "10000",
        "LE_gain": "85",
        "STR_gain": "65",
        "VE_gain": "85",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "4",
        "BeastId": "117"
    },
    {
        "Name": "Chimera",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "45",
        "STR_gain": "35",
        "VE_gain": "45",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "115"
    },
    {
        "Name": "Greenbull",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "43"
    },
    {
        "Name": "Reindeer",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "51"
    },
    {
        "Name": "Black Kyrin",
        "Star": "4",
        "LE": "6000",
        "STR": "5500",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "45"
    },
    {
        "Name": "Panda",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "58"
    },
    {
        "Name": "Koi",
        "Star": "4",
        "LE": "5500",
        "STR": "5500",
        "VE": "5500",
        "DEX": "5500",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "39"
    },
    {
        "Name": "Jade Rabbit",
        "Star": "4",
        "LE": "6000",
        "STR": "5500",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "47"
    },
    {
        "Name": "Chroma Dragon",
        "Star": "6",
        "LE": "12500",
        "STR": "12500",
        "VE": "15000",
        "DEX": "10000",
        "LE_gain": "75",
        "STR_gain": "75",
        "VE_gain": "90",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "4",
        "BeastId": "142"
    },
    {
        "Name": "Cloud Griffin",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "78"
    },
    {
        "Name": "Zouwu",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "73"
    },
    {
        "Name": "Chi Wen",
        "Star": "4",
        "LE": "5500",
        "STR": "4000",
        "VE": "5500",
        "DEX": "7000",
        "LE_gain": "40",
        "STR_gain": "25",
        "VE_gain": "40",
        "DEX_gain": "55",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "99"
    },
    {
        "Name": "Snow Princess",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "71"
    },
    {
        "Name": "Water Kirin",
        "Star": "4",
        "LE": "8000",
        "STR": "4000",
        "VE": "4500",
        "DEX": "5500",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "35",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "91"
    },
    {
        "Name": "Destiny",
        "Star": "4",
        "LE": "5500",
        "STR": "6000",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "53"
    },
    {
        "Name": "Sky Phoenix",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "68"
    },
    {
        "Name": "Dark Devourer",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "34"
    },
    {
        "Name": "Devour",
        "Star": "4",
        "LE": "5500",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5500",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "33"
    },
    {
        "Name": "Shadow Lord",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "62"
    },
    {
        "Name": "Feifei",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "45",
        "STR_gain": "35",
        "VE_gain": "45",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "123"
    },
    {
        "Name": "Snow Bear",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "7000",
        "DEX": "4000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "50",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "81"
    },
    {
        "Name": "Dancing Lion",
        "Star": "4",
        "LE": "8000",
        "STR": "4500",
        "VE": "5000",
        "DEX": "4500",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "40",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "83"
    },
    {
        "Name": "Shenpan",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "55"
    },
    {
        "Name": "Tianhu",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "56"
    },
    {
        "Name": "Bixi",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "57"
    },
    {
        "Name": "Ruyi Bunny",
        "Star": "4",
        "LE": "6000",
        "STR": "4000",
        "VE": "4000",
        "DEX": "8000",
        "LE_gain": "40",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "107"
    },
    {
        "Name": "Kun Peng",
        "Star": "4",
        "LE": "5000",
        "STR": "5500",
        "VE": "7000",
        "DEX": "4500",
        "LE_gain": "35",
        "STR_gain": "45",
        "VE_gain": "50",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "136"
    },
    {
        "Name": "Azure Spirit Fox",
        "Star": "4",
        "LE": "6500",
        "STR": "4000",
        "VE": "6500",
        "DEX": "5000",
        "LE_gain": "50",
        "STR_gain": "25",
        "VE_gain": "50",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "152"
    },
    {
        "Name": "Dragon Horse",
        "Star": "4",
        "LE": "6000",
        "STR": "6000",
        "VE": "5000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "49"
    },
    {
        "Name": "Elephant",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "64"
    },
    {
        "Name": "Dragon Ancestor",
        "Star": "6",
        "LE": "18000",
        "STR": "18000",
        "VE": "18000",
        "DEX": "18000",
        "LE_gain": "90",
        "STR_gain": "90",
        "VE_gain": "90",
        "DEX_gain": "90",
        "ServantIds": "55,56,57",
        "Region_Boost": "0.2",
        "Region": "",
        "BeastId": "66"
    },
    {
        "Name": "Cyan Phoenix",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "67"
    },
    {
        "Name": "Glory Feilian",
        "Star": "4",
        "LE": "5500",
        "STR": "4000",
        "VE": "5500",
        "DEX": "7000",
        "LE_gain": "40",
        "STR_gain": "25",
        "VE_gain": "40",
        "DEX_gain": "55",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "103"
    },
    {
        "Name": "Baby Celestial Deer",
        "Star": "4",
        "LE": "5000",
        "STR": "6000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "35",
        "STR_gain": "45",
        "VE_gain": "45",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "132"
    },
    {
        "Name": "Snow",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "70"
    },
    {
        "Name": "Deity phoenix",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "30"
    },
    {
        "Name": "Lucky Fly Dragon",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "38"
    },
    {
        "Name": "Nimbus Kirin",
        "Star": "4",
        "LE": "6000",
        "STR": "5400",
        "VE": "6000",
        "DEX": "4600",
        "LE_gain": "45",
        "STR_gain": "40",
        "VE_gain": "45",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "144"
    },
    {
        "Name": "Mermaid",
        "Star": "4",
        "LE": "5000",
        "STR": "6500",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "35",
        "STR_gain": "50",
        "VE_gain": "40",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "156"
    },
    {
        "Name": "QueenBird",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "28"
    },
    {
        "Name": "Anhar",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "76"
    },
    {
        "Name": "Fortune Dragon",
        "Star": "4",
        "LE": "5500",
        "STR": "5500",
        "VE": "7000",
        "DEX": "4000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "50",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "140"
    },
    {
        "Name": "Fuzhu",
        "Star": "4",
        "LE": "7000",
        "STR": "4000",
        "VE": "4000",
        "DEX": "7000",
        "LE_gain": "50",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "95"
    },
    {
        "Name": "Gale Fairy",
        "Star": "6",
        "LE": "13000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "16000",
        "LE_gain": "65",
        "STR_gain": "60",
        "VE_gain": "60",
        "DEX_gain": "75",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "4",
        "BeastId": "110"
    },
    {
        "Name": "Dudu",
        "Star": "3",
        "LE": "2500",
        "STR": "2500",
        "VE": "3500",
        "DEX": "2000",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "80"
    },
    {
        "Name": "Thunder Phoenix",
        "Star": "4",
        "LE": "6500",
        "STR": "5000",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "40",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "148"
    },
    {
        "Name": "Deity QingYuan",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "32"
    },
    {
        "Name": "King Koi",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "40"
    },
    {
        "Name": "Moon Rabbit",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "48"
    },
    {
        "Name": "Destiny of God",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "54"
    },
    {
        "Name": "Heavenly Phoenix",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "69"
    },
    {
        "Name": "Three-tailed Fox",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "87"
    },
    {
        "Name": "Six-tailed Fox",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "5000",
        "DEX": "6000",
        "LE_gain": "45",
        "STR_gain": "35",
        "VE_gain": "35",
        "DEX_gain": "45",
        "ServantIds": "75",
        "Region_Boost": "0.12",
        "Region": "",
        "BeastId": "88"
    },
    {
        "Name": "Nine-tailed Fox",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "89"
    },
    {
        "Name": "Waterin",
        "Star": "3",
        "LE": "2500",
        "STR": "2000",
        "VE": "2500",
        "DEX": "3500",
        "LE_gain": "30",
        "STR_gain": "25",
        "VE_gain": "30",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "90"
    },
    {
        "Name": "Dark Kyrin",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "46"
    },
    {
        "Name": "Might Panda",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "59"
    },
    {
        "Name": "Snow Queen",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "72"
    },
    {
        "Name": "Griffin",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "77"
    },
    {
        "Name": "Immortal Eater",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "26"
    },
    {
        "Name": "Immortal Elephant",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "65"
    },
    {
        "Name": "Lunar Fuzhu",
        "Star": "6",
        "LE": "15000",
        "STR": "10000",
        "VE": "10000",
        "DEX": "15000",
        "LE_gain": "85",
        "STR_gain": "65",
        "VE_gain": "65",
        "DEX_gain": "85",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "4",
        "BeastId": "97"
    },
    {
        "Name": "River Carp",
        "Star": "3",
        "LE": "2500",
        "STR": "2000",
        "VE": "2500",
        "DEX": "3500",
        "LE_gain": "30",
        "STR_gain": "20",
        "VE_gain": "30",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "98"
    },
    {
        "Name": "Purple Thunder",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "36"
    },
    {
        "Name": "Qing Greenbull",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "44"
    },
    {
        "Name": "Shadow Monster",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "61"
    },
    {
        "Name": "Snowy Reindeer",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "52"
    },
    {
        "Name": "Scarlet Flames Zouwu",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "74"
    },
    {
        "Name": "Oceanic Chi Wen",
        "Star": "5",
        "LE": "8000",
        "STR": "5500",
        "VE": "8000",
        "DEX": "10500",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "50",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "100"
    },
    {
        "Name": "Feilian",
        "Star": "3",
        "LE": "2500",
        "STR": "2000",
        "VE": "2500",
        "DEX": "3500",
        "LE_gain": "30",
        "STR_gain": "20",
        "VE_gain": "30",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "102"
    },
    {
        "Name": "Frost Howler",
        "Star": "5",
        "LE": "8500",
        "STR": "7500",
        "VE": "10000",
        "DEX": "6000",
        "LE_gain": "45",
        "STR_gain": "45",
        "VE_gain": "70",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "82"
    },
    {
        "Name": "Blazing Lion",
        "Star": "5",
        "LE": "11000",
        "STR": "6500",
        "VE": "8000",
        "DEX": "6500",
        "LE_gain": "60",
        "STR_gain": "45",
        "VE_gain": "50",
        "DEX_gain": "45",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "84"
    },
    {
        "Name": "Charming Feilian",
        "Star": "5",
        "LE": "8000",
        "STR": "5500",
        "VE": "8000",
        "DEX": "10500",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "50",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "104"
    },
    {
        "Name": "Spirit Bunny",
        "Star": "3",
        "LE": "3000",
        "STR": "2000",
        "VE": "2000",
        "DEX": "3500",
        "LE_gain": "30",
        "STR_gain": "25",
        "VE_gain": "25",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "106"
    },
    {
        "Name": "Tidal Kirin",
        "Star": "5",
        "LE": "11000",
        "STR": "6000",
        "VE": "7000",
        "DEX": "8000",
        "LE_gain": "60",
        "STR_gain": "40",
        "VE_gain": "45",
        "DEX_gain": "55",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "92"
    },
    {
        "Name": "Jade Bunny",
        "Star": "5",
        "LE": "8000",
        "STR": "6000",
        "VE": "6000",
        "DEX": "12000",
        "LE_gain": "50",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "108"
    },
    {
        "Name": "Tidal Kun Peng",
        "Star": "5",
        "LE": "7500",
        "STR": "8000",
        "VE": "10000",
        "DEX": "6500",
        "LE_gain": "45",
        "STR_gain": "55",
        "VE_gain": "65",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "137"
    },
    {
        "Name": "Majestic Dragon",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "10000",
        "DEX": "6000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "65",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "141"
    },
    {
        "Name": "Shadow Immortal",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "63"
    },
    {
        "Name": "Ice Celestial Deer",
        "Star": "5",
        "LE": "7000",
        "STR": "9000",
        "VE": "9000",
        "DEX": "7000",
        "LE_gain": "40",
        "STR_gain": "60",
        "VE_gain": "60",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "133"
    },
    {
        "Name": "Charm Spirit Fox",
        "Star": "5",
        "LE": "9000",
        "STR": "6500",
        "VE": "9000",
        "DEX": "7500",
        "LE_gain": "60",
        "STR_gain": "35",
        "VE_gain": "60",
        "DEX_gain": "45",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "153"
    },
    {
        "Name": "Mera",
        "Star": "3",
        "LE": "3000",
        "STR": "2250",
        "VE": "3000",
        "DEX": "2250",
        "LE_gain": "35",
        "STR_gain": "25",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "114"
    },
    {
        "Name": "Mechanical Vermilion Bird",
        "Star": "6",
        "LE": "13500",
        "STR": "9500",
        "VE": "12500",
        "DEX": "9500",
        "LE_gain": "75",
        "STR_gain": "60",
        "VE_gain": "65",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "4",
        "BeastId": "130"
    },
    {
        "Name": "Monster Nian",
        "Star": "4",
        "LE": "5500",
        "STR": "5000",
        "VE": "6000",
        "DEX": "5500",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "25"
    },
    {
        "Name": "Phantom Lion",
        "Star": "6",
        "LE": "12500",
        "STR": "11500",
        "VE": "11500",
        "DEX": "10000",
        "LE_gain": "65",
        "STR_gain": "65",
        "VE_gain": "65",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "4",
        "BeastId": "79"
    },
    {
        "Name": "Picapica",
        "Star": "4",
        "LE": "6000",
        "STR": "5000",
        "VE": "5000",
        "DEX": "6000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "41"
    },
    {
        "Name": "Spiritual Feifei",
        "Star": "5",
        "LE": "9000",
        "STR": "7000",
        "VE": "9000",
        "DEX": "7000",
        "LE_gain": "60",
        "STR_gain": "40",
        "VE_gain": "60",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "124"
    },
    {
        "Name": "Celestial Thunder Phoenix",
        "Star": "5",
        "LE": "10000",
        "STR": "7000",
        "VE": "8000",
        "DEX": "7000",
        "LE_gain": "70",
        "STR_gain": "40",
        "VE_gain": "50",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "149"
    },
    {
        "Name": "Immortal Panda",
        "Star": "6",
        "LE": "12500",
        "STR": "12500",
        "VE": "12500",
        "DEX": "12500",
        "LE_gain": "75",
        "STR_gain": "75",
        "VE_gain": "75",
        "DEX_gain": "75",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "60"
    },
    {
        "Name": "Baby Fei",
        "Star": "3",
        "LE": "3000",
        "STR": "2250",
        "VE": "3000",
        "DEX": "2250",
        "LE_gain": "35",
        "STR_gain": "25",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "122"
    },
    {
        "Name": "Zenith Kirin",
        "Star": "5",
        "LE": "8650",
        "STR": "8000",
        "VE": "8650",
        "DEX": "6700",
        "LE_gain": "55",
        "STR_gain": "50",
        "VE_gain": "55",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "145"
    },
    {
        "Name": "Siren Songstress",
        "Star": "5",
        "LE": "7000",
        "STR": "9500",
        "VE": "8500",
        "DEX": "7000",
        "LE_gain": "45",
        "STR_gain": "60",
        "VE_gain": "50",
        "DEX_gain": "45",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "157"
    },
    {
        "Name": "Golden Flames Zouwu",
        "Star": "6",
        "LE": "12500",
        "STR": "12500",
        "VE": "12500",
        "DEX": "12500",
        "LE_gain": "75",
        "STR_gain": "75",
        "VE_gain": "75",
        "DEX_gain": "75",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "3",
        "BeastId": "75"
    },
    {
        "Name": "Fortune Pup",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "40",
        "STR_gain": "25",
        "VE_gain": "30",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "126"
    },
    {
        "Name": "Sky Howler",
        "Star": "4",
        "LE": "6500",
        "STR": "5000",
        "VE": "5500",
        "DEX": "5000",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "40",
        "DEX_gain": "35",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.12",
        "Region": "",
        "BeastId": "127"
    },
    {
        "Name": "Shadow Howler",
        "Star": "5",
        "LE": "10000",
        "STR": "7000",
        "VE": "8000",
        "DEX": "7000",
        "LE_gain": "70",
        "STR_gain": "40",
        "VE_gain": "50",
        "DEX_gain": "40",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.15",
        "Region": "",
        "BeastId": "128"
    },
    {
        "Name": "Divine Howler",
        "Star": "6",
        "LE": "17000",
        "STR": "10000",
        "VE": "13000",
        "DEX": "10000",
        "LE_gain": "95",
        "STR_gain": "65",
        "VE_gain": "75",
        "DEX_gain": "65",
        "ServantIds": "44,45,47,50",
        "Region_Boost": "0.18",
        "Region": "",
        "BeastId": "129"
    },
    {
        "Name": "Star Picapica",
        "Star": "5",
        "LE": "8000",
        "STR": "8000",
        "VE": "8000",
        "DEX": "8000",
        "LE_gain": "50",
        "STR_gain": "50",
        "VE_gain": "50",
        "DEX_gain": "50",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "42"
    },
    {
        "Name": "Deer Spirit",
        "Star": "3",
        "LE": "2400",
        "STR": "2850",
        "VE": "2850",
        "DEX": "2400",
        "LE_gain": "25",
        "STR_gain": "35",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "131"
    },
    {
        "Name": "Inferno Lion",
        "Star": "6",
        "LE": "15000",
        "STR": "11000",
        "VE": "13000",
        "DEX": "11000",
        "LE_gain": "85",
        "STR_gain": "70",
        "VE_gain": "75",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "85"
    },
    {
        "Name": "Cosmic Stars Feilian",
        "Star": "6",
        "LE": "12500",
        "STR": "10000",
        "VE": "12500",
        "DEX": "15000",
        "LE_gain": "75",
        "STR_gain": "65",
        "VE_gain": "75",
        "DEX_gain": "85",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "105"
    },
    {
        "Name": "Crystal Serpent",
        "Star": "6",
        "LE": "10000",
        "STR": "8500",
        "VE": "16500",
        "DEX": "10000",
        "LE_gain": "65",
        "STR_gain": "60",
        "VE_gain": "70",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "1",
        "BeastId": "112"
    },
    {
        "Name": "Sea Kun",
        "Star": "3",
        "LE": "2600",
        "STR": "2700",
        "VE": "3100",
        "DEX": "2100",
        "LE_gain": "25",
        "STR_gain": "30",
        "VE_gain": "40",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "135"
    },
    {
        "Name": "Tsunami Kirin",
        "Star": "6",
        "LE": "15000",
        "STR": "10000",
        "VE": "12000",
        "DEX": "13000",
        "LE_gain": "85",
        "STR_gain": "65",
        "VE_gain": "70",
        "DEX_gain": "80",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "93"
    },
    {
        "Name": "Immortal Bunny",
        "Star": "6",
        "LE": "13000",
        "STR": "10000",
        "VE": "10000",
        "DEX": "17000",
        "LE_gain": "80",
        "STR_gain": "65",
        "VE_gain": "65",
        "DEX_gain": "90",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "109"
    },
    {
        "Name": "Thunder Empress",
        "Star": "6",
        "LE": "16000",
        "STR": "12000",
        "VE": "8000",
        "DEX": "9000",
        "LE_gain": "75",
        "STR_gain": "65",
        "VE_gain": "60",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "2",
        "BeastId": "113"
    },
    {
        "Name": "Dragon Spirit",
        "Star": "3",
        "LE": "2500",
        "STR": "2500",
        "VE": "3100",
        "DEX": "2400",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "40",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "139"
    },
    {
        "Name": "Stellar Fuzhu",
        "Star": "5",
        "LE": "10000",
        "STR": "6000",
        "VE": "6000",
        "DEX": "10000",
        "LE_gain": "60",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "96"
    },
    {
        "Name": "Yoo-Yoo",
        "Star": "3",
        "LE": "3250",
        "STR": "2000",
        "VE": "2000",
        "DEX": "3250",
        "LE_gain": "35",
        "STR_gain": "25",
        "VE_gain": "25",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.06",
        "Region": "4",
        "BeastId": "94"
    },
    {
        "Name": "Zhuyan",
        "Star": "4",
        "LE": "5500",
        "STR": "5000",
        "VE": "5000",
        "DEX": "5000",
        "LE_gain": "40",
        "STR_gain": "40",
        "VE_gain": "40",
        "DEX_gain": "40",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "15"
    },
    {
        "Name": "Heavenly Kirin",
        "Star": "3",
        "LE": "2850",
        "STR": "2600",
        "VE": "2850",
        "DEX": "2200",
        "LE_gain": "35",
        "STR_gain": "30",
        "VE_gain": "35",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "143"
    },
    {
        "Name": "Dragon Chi Wen",
        "Star": "6",
        "LE": "13000",
        "STR": "7000",
        "VE": "10000",
        "DEX": "15000",
        "LE_gain": "65",
        "STR_gain": "50",
        "VE_gain": "65",
        "DEX_gain": "80",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "3",
        "BeastId": "101"
    },
    {
        "Name": "Inferno Bloom",
        "Star": "6",
        "LE": "16500",
        "STR": "9000",
        "VE": "9000",
        "DEX": "10500",
        "LE_gain": "75",
        "STR_gain": "60",
        "VE_gain": "60",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "3",
        "BeastId": "111"
    },
    {
        "Name": "Hellhound",
        "Star": "6",
        "LE": "11500",
        "STR": "9000",
        "VE": "13000",
        "DEX": "11500",
        "LE_gain": "65",
        "STR_gain": "60",
        "VE_gain": "70",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "3",
        "BeastId": "119"
    },
    {
        "Name": "Thunder Sparrow",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2500",
        "DEX": "2500",
        "LE_gain": "40",
        "STR_gain": "25",
        "VE_gain": "30",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "147"
    },
    {
        "Name": "Santan Kingkong",
        "Star": "6",
        "LE": "10000",
        "STR": "10000",
        "VE": "15000",
        "DEX": "10000",
        "LE_gain": "60",
        "STR_gain": "60",
        "VE_gain": "80",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "1",
        "BeastId": "120"
    },
    {
        "Name": "Christmas Celestial Deer",
        "Star": "6",
        "LE": "11000",
        "STR": "14000",
        "VE": "14000",
        "DEX": "11000",
        "LE_gain": "65",
        "STR_gain": "85",
        "VE_gain": "85",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "134"
    },
    {
        "Name": "Heaven-Splitting Thunder Phoenix",
        "Star": "6",
        "LE": "14500",
        "STR": "11500",
        "VE": "12500",
        "DEX": "11500",
        "LE_gain": "85",
        "STR_gain": "70",
        "VE_gain": "75",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "150"
    },
    {
        "Name": "Spirit Fox",
        "Star": "3",
        "LE": "3000",
        "STR": "2000",
        "VE": "3000",
        "DEX": "2500",
        "LE_gain": "35",
        "STR_gain": "25",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "151"
    },
    {
        "Name": "Nightshade Serpent",
        "Star": "6",
        "LE": "12000",
        "STR": "8000",
        "VE": "11000",
        "DEX": "14000",
        "LE_gain": "65",
        "STR_gain": "60",
        "VE_gain": "65",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.17",
        "Region": "2",
        "BeastId": "121"
    },
    {
        "Name": "Heavenly Kun Peng",
        "Star": "6",
        "LE": "11500",
        "STR": "13000",
        "VE": "15000",
        "DEX": "10500",
        "LE_gain": "70",
        "STR_gain": "80",
        "VE_gain": "90",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "138"
    },
    {
        "Name": "Empress Spirit Fox",
        "Star": "6",
        "LE": "14000",
        "STR": "10500",
        "VE": "14000",
        "DEX": "11500",
        "LE_gain": "85",
        "STR_gain": "60",
        "VE_gain": "85",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "154"
    },
    {
        "Name": "Fish Spirit",
        "Star": "3",
        "LE": "2400",
        "STR": "3000",
        "VE": "2700",
        "DEX": "2400",
        "LE_gain": "25",
        "STR_gain": "40",
        "VE_gain": "30",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "155"
    },
    {
        "Name": "Celestial Feifei",
        "Star": "6",
        "LE": "14000",
        "STR": "11000",
        "VE": "14000",
        "DEX": "11000",
        "LE_gain": "85",
        "STR_gain": "65",
        "VE_gain": "85",
        "DEX_gain": "65",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "3",
        "BeastId": "125"
    },
    {
        "Name": "Heaven Soaring Kirin",
        "Star": "6",
        "LE": "13500",
        "STR": "12500",
        "VE": "13500",
        "DEX": "10500",
        "LE_gain": "85",
        "STR_gain": "70",
        "VE_gain": "85",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "3",
        "BeastId": "146"
    },
    {
        "Name": "Ocean Diva",
        "Star": "6",
        "LE": "11000",
        "STR": "14500",
        "VE": "13000",
        "DEX": "11500",
        "LE_gain": "65",
        "STR_gain": "85",
        "VE_gain": "80",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "3",
        "BeastId": "158"
    },
    {
        "Name": "Mecha Dragon",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "2800",
        "DEX": "2200",
        "LE_gain": "40",
        "STR_gain": "25",
        "VE_gain": "30",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "159"
    },
    {
        "Name": "Mecha Tyrant Dragon",
        "Star": "4",
        "LE": "6500",
        "STR": "5000",
        "VE": "6000",
        "DEX": "4500",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "45",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "160"
    },
    {
        "Name": "Mecha Dark Dragon",
        "Star": "5",
        "LE": "9500",
        "STR": "7500",
        "VE": "8500",
        "DEX": "6500",
        "LE_gain": "65",
        "STR_gain": "45",
        "VE_gain": "55",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "161"
    },
    {
        "Name": "Nidhogg",
        "Star": "6",
        "LE": "14500",
        "STR": "12000",
        "VE": "13500",
        "DEX": "10000",
        "LE_gain": "90",
        "STR_gain": "70",
        "VE_gain": "80",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "162"
    },
    {
        "Name": "Baby Zouwu",
        "Star": "3",
        "LE": "2700",
        "STR": "2600",
        "VE": "2600",
        "DEX": "2600",
        "LE_gain": "30",
        "STR_gain": "30",
        "VE_gain": "30",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "163"
    },
    {
        "Name": "Baby Taowu",
        "Star": "3",
        "LE": "2700",
        "STR": "2500",
        "VE": "3200",
        "DEX": "2100",
        "LE_gain": "30",
        "STR_gain": "25",
        "VE_gain": "40",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "164"
    },
    {
        "Name": "Taowu",
        "Star": "4",
        "LE": "5500",
        "STR": "5000",
        "VE": "7000",
        "DEX": "4500",
        "LE_gain": "45",
        "STR_gain": "35",
        "VE_gain": "50",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "2",
        "BeastId": "165"
    },
    {
        "Name": "Mountain Guardian Taowu",
        "Star": "5",
        "LE": "8000",
        "STR": "7500",
        "VE": "10000",
        "DEX": "6500",
        "LE_gain": "55",
        "STR_gain": "45",
        "VE_gain": "65",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "2",
        "BeastId": "166"
    },
    {
        "Name": "Dragon Conqueror Taowu",
        "Star": "6",
        "LE": "12500",
        "STR": "12000",
        "VE": "15500",
        "DEX": "10000",
        "LE_gain": "80",
        "STR_gain": "70",
        "VE_gain": "90",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "2",
        "BeastId": "167"
    },
    {
        "Name": "Snow Spirit",
        "Star": "3",
        "LE": "2400",
        "STR": "3150",
        "VE": "2950",
        "DEX": "2000",
        "LE_gain": "30",
        "STR_gain": "35",
        "VE_gain": "35",
        "DEX_gain": "20",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "168"
    },
    {
        "Name": "Snowgirl",
        "Star": "4",
        "LE": "5000",
        "STR": "6600",
        "VE": "6200",
        "DEX": "4200",
        "LE_gain": "35",
        "STR_gain": "50",
        "VE_gain": "45",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "4",
        "BeastId": "169"
    },
    {
        "Name": "Snow Maiden",
        "Star": "5",
        "LE": "7300",
        "STR": "9500",
        "VE": "9000",
        "DEX": "6200",
        "LE_gain": "45",
        "STR_gain": "65",
        "VE_gain": "60",
        "DEX_gain": "30",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "4",
        "BeastId": "170"
    },
    {
        "Name": "Snow Queen",
        "Star": "6",
        "LE": "11500",
        "STR": "15000",
        "VE": "14000",
        "DEX": "9500",
        "LE_gain": "70",
        "STR_gain": "90",
        "VE_gain": "85",
        "DEX_gain": "55",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "4",
        "BeastId": "171"
    },
    {
        "Name": "Fortune Pixiu",
        "Star": "3",
        "LE": "3000",
        "STR": "2500",
        "VE": "3000",
        "DEX": "2000",
        "LE_gain": "35",
        "STR_gain": "25",
        "VE_gain": "35",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "172"
    },
    {
        "Name": "Blessed Pixiu",
        "Star": "4",
        "LE": "6500",
        "STR": "5000",
        "VE": "6500",
        "DEX": "4000",
        "LE_gain": "50",
        "STR_gain": "35",
        "VE_gain": "50",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "3",
        "BeastId": "173"
    },
    {
        "Name": "Royal Pixiu",
        "Star": "5",
        "LE": "9000",
        "STR": "7500",
        "VE": "9000",
        "DEX": "6500",
        "LE_gain": "60",
        "STR_gain": "45",
        "VE_gain": "60",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "3",
        "BeastId": "174"
    },
    {
        "Name": "Celestial Pixiu",
        "Star": "6",
        "LE": "14000",
        "STR": "11500",
        "VE": "14000",
        "DEX": "10500",
        "LE_gain": "85",
        "STR_gain": "70",
        "VE_gain": "85",
        "DEX_gain": "60",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "3",
        "BeastId": "175"
    },
    {
        "Name": "Star Dream",
        "Star": "3",
        "LE": "2400",
        "STR": "2700",
        "VE": "3000",
        "DEX": "2400",
        "LE_gain": "25",
        "STR_gain": "30",
        "VE_gain": "40",
        "DEX_gain": "25",
        "ServantIds": "",
        "Region_Boost": "",
        "Region": "",
        "BeastId": "176"
    },
    {
        "Name": "Gemini Star Spirit",
        "Star": "4",
        "LE": "5000",
        "STR": "5500",
        "VE": "6500",
        "DEX": "5000",
        "LE_gain": "35",
        "STR_gain": "40",
        "VE_gain": "50",
        "DEX_gain": "35",
        "ServantIds": "",
        "Region_Boost": "0.12",
        "Region": "1",
        "BeastId": "177"
    },
    {
        "Name": "Yin Yang Immortal Spirit",
        "Star": "5",
        "LE": "7000",
        "STR": "8500",
        "VE": "9500",
        "DEX": "7000",
        "LE_gain": "45",
        "STR_gain": "50",
        "VE_gain": "60",
        "DEX_gain": "45",
        "ServantIds": "",
        "Region_Boost": "0.15",
        "Region": "1",
        "BeastId": "178"
    },
    {
        "Name": "Cosmic Sovereign",
        "Star": "6",
        "LE": "11000",
        "STR": "13000",
        "VE": "14500",
        "DEX": "11500",
        "LE_gain": "65",
        "STR_gain": "80",
        "VE_gain": "85",
        "DEX_gain": "70",
        "ServantIds": "",
        "Region_Boost": "0.18",
        "Region": "1",
        "BeastId": "179"
    }
]